
---
meta:
  name: habitat
  target: sw
  url:     https://ci.starkandwayne.com
  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))
  github:
    owner: starkandwayne
    repo:  habitat-boshrelease
    private_key:  (( vault "secret/pipelines/habitat-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/habitat-boshrelease/github:token" ))
  bosh-lite:
    target: https://10.58.111.46:25555
    deployment: habitat-warden
  slack:
    webhook: (( vault "secret/pipelines/habitat-boshrelease/slack:webhook" ))
    channel: "#cf-community-pipeline"
