#!/bin/bash -e

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

ls -ln

header "Deploying Bosh"

start-bosh

source /tmp/local-bosh/director/env

header "Upload stemcell"
bosh -n upload-stemcell $stemcell

cd ${REPO_ROOT}

header "creating release"
bosh -n create-release
bosh -n upload-release --rebase || echo "Continuing..."

header "Deploying $deploymentname with $manifest"
bosh -n deploy $manifest -d $deploymentname

echo
echo "SUCCESS"
exit 0
