---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: git

outputs:
  - name: sources

params:
  manifest: (( grab meta.bosh-lite.manifest ))
  deploymentname: (( grab meta.bosh-lite.deployment ))

run:
  path: git/ci/tasks/local-bosh/task
