---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: git

outputs:
  - name: sources

params: []

run:
  path: git/ci/tasks/local-bosh/task
