---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker
    privileged: true

inputs:
  - name: git

params: []

run:
  path: git/ci/tasks/local-bosh/task
