---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: git
  - name: resource-bosh-stemcell

params:
  REPO_ROOT: replaceme
  manifest: replaceme
  deploymentname: replaceme
  stemcell: replaceme

run:
  path: git/ci/tasks/local-bosh/task
